import Link from "@docusaurus/Link";
import Translate, { translate } from "@docusaurus/Translate";
import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
import CodeBlock from "@theme/CodeBlock";
import Layout from "@theme/Layout";
import { useEffect, useState, type ReactNode } from "react";
import { preferredLocale } from "../locale-preference";

const INSTALL = "npm install @hoyasumii/linkedin";

interface Feature {
  label: string;
  title: string;
  to: string;
  description: ReactNode;
  sample: string;
  language: string;
}

/** Built per render, so `translate` runs with the page's locale loaded. */
function features(): Feature[] {
  return [
    {
      label: "linkedin-mcp",
      title: translate({ id: "home.mcp.title", message: "MCP server" }),
      to: "/docs/mcp/overview",
      description: (
        <Translate id="home.mcp.description">
          Let Claude Code, Codex, OpenCode or any MCP client post for you: text, images, a video, a document or a link;
          edit the text later, or delete the post.
        </Translate>
      ),
      language: "bash",
      sample: `npx -p @hoyasumii/linkedin linkedin mcp config --web
npx -p @hoyasumii/linkedin linkedin mcp install`,
    },
    {
      label: "@hoyasumii/linkedin",
      title: "SDK",
      to: "/docs/sdk/overview",
      description: (
        <Translate id="home.sdk.description">
          A typed client for LinkedIn's Posts API, generated by orval from an OpenAPI spec: uploads, multi-part videos
          and the little text format handled for you.
        </Translate>
      ),
      language: "ts",
      sample: `const linkedin = createLinkedInClient({ accessToken });
const { urn } = await linkedin.createPost({ text: "Shipped (finally)!" });`,
    },
    {
      label: "linkedin",
      title: "CLI",
      to: "/docs/cli/overview",
      description: (
        <Translate id="home.cli.description">
          Sign in to LinkedIn from a local web page, and register the MCP server in your AI clients in one go.
        </Translate>
      ),
      language: "bash",
      sample: `linkedin mcp status
linkedin mcp install --client claude`,
    },
  ];
}

function InstallCommand(): ReactNode {
  const [copied, setCopied] = useState(false);
  const copy = () => {
    void navigator.clipboard.writeText(INSTALL).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };
  return (
    <div className="home-install">
      <code style={{ all: "unset" }}>
        <span>$ </span>
        {INSTALL}
      </code>
      <button type="button" onClick={copy}>
        {copied ? (
          <Translate id="home.install.copied">Copied</Translate>
        ) : (
          <Translate id="home.install.copy">Copy</Translate>
        )}
      </button>
    </div>
  );
}

/**
 * On the English home page only, sends the visitor to the translation that matches the language they
 * picked in the navbar menu or, failing that, their browser's. Every other page, translated homes
 * included, stays where its link pointed.
 */
function useLocaleRedirect(): void {
  const { i18n } = useDocusaurusContext();
  useEffect(() => {
    if (i18n.currentLocale !== i18n.defaultLocale) return;
    const locale = preferredLocale(i18n.locales);
    if (!locale || locale === i18n.currentLocale) return;
    const { search, hash } = window.location;
    window.location.replace(`${i18n.localeConfigs[locale]!.baseUrl}${search}${hash}`);
  }, [i18n]);
}

export default function Home(): ReactNode {
  const { siteConfig } = useDocusaurusContext();
  useLocaleRedirect();
  return (
    <Layout
      title={translate({ id: "home.title", message: "LinkedIn MCP server and SDK" })}
      description={siteConfig.tagline}
    >
      <header className="home-hero">
        <div className="container">
          <span className="home-badge">
            <Translate id="home.badge">TypeScript · LinkedIn · MCP · SDK</Translate>
          </span>
          <h1 className="home-title">
            <Translate id="home.headline">Your LinkedIn posts, from your AI agent</Translate>
          </h1>
          <p className="home-subtitle">
            <Translate id="home.tagline">
              An unofficial MCP server and TypeScript SDK to create, edit and delete your own LinkedIn posts, through
              LinkedIn's official API and an app of your own.
            </Translate>
          </p>
          <div className="home-actions">
            <Link className="home-button home-button--primary" to="/docs/intro">
              <Translate id="home.getStarted">Get started</Translate> →
            </Link>
            <Link className="home-button home-button--ghost" to="https://github.com/Hoyasumii/linkedin">
              GitHub
            </Link>
          </div>
          <InstallCommand />
        </div>
      </header>
      <main className="container">
        <div className="home-features">
          {features().map((feature) => (
            <div key={feature.title} className="home-card">
              <span className="home-card__label">{feature.label}</span>
              <h3>
                <Link to={feature.to}>{feature.title}</Link>
              </h3>
              <p>{feature.description}</p>
              <CodeBlock language={feature.language}>{feature.sample}</CodeBlock>
            </div>
          ))}
        </div>
      </main>
    </Layout>
  );
}
